"""Popcorn: kernel dispatch for PyTorch -- torch references, optimized backends,
autogenerated correctness and benchmarks."""

import os

# Triton lowers fp32 matmuls to tf32 by default, which silently breaks float32
# parity with the torch reference. Kernels keep tensor-core speed on 16-bit
# inputs; float32 means ieee float32.
os.environ.setdefault("TRITON_F32_DEFAULT", "ieee")

from popcorn.core import *  # noqa: E402,F401,F403
from popcorn.core import __all__  # noqa: E402,F401
